name: Consistency proof

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch:

permissions: read-all

jobs:
  run_consistency_proof:
    permissions:
      contents: read
      issues: write
      id-token: write
    uses: sigstore/rekor-monitor/.github/workflows/reusable_monitoring.yml@main
    with:
      file_issue: true
      identities: |
        certIdentities:
          - certSubject: hblauzvern@google.com
        subjects:
          - hblauzvern@google.com
