name: Consistency proof

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch:

permissions: read-all

jobs:
  run_consistency_proof:
    permissions:
      contents: read
      issues: write
      id-token: write
    uses: haydentherapper/rekor-monitor/.github/workflows/reusable_monitoring.yml@reusable-workflow-right
    with:
      file_issue: true

